// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.9
// source: billing.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateLoanRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LoanId          string                 `protobuf:"bytes,1,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`
	CustomerId      string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	PrincipalAmount int64                  `protobuf:"varint,3,opt,name=principal_amount,json=principalAmount,proto3" json:"principal_amount,omitempty"`
	TenureWeeks     int32                  `protobuf:"varint,4,opt,name=tenure_weeks,json=tenureWeeks,proto3" json:"tenure_weeks,omitempty"`
	InterestRate    float64                `protobuf:"fixed64,5,opt,name=interest_rate,json=interestRate,proto3" json:"interest_rate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateLoanRequest) Reset() {
	*x = CreateLoanRequest{}
	mi := &file_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLoanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLoanRequest) ProtoMessage() {}

func (x *CreateLoanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLoanRequest.ProtoReflect.Descriptor instead.
func (*CreateLoanRequest) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLoanRequest) GetLoanId() string {
	if x != nil {
		return x.LoanId
	}
	return ""
}

func (x *CreateLoanRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreateLoanRequest) GetPrincipalAmount() int64 {
	if x != nil {
		return x.PrincipalAmount
	}
	return 0
}

func (x *CreateLoanRequest) GetTenureWeeks() int32 {
	if x != nil {
		return x.TenureWeeks
	}
	return 0
}

func (x *CreateLoanRequest) GetInterestRate() float64 {
	if x != nil {
		return x.InterestRate
	}
	return 0
}

type CreateLoanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLoanResponse) Reset() {
	*x = CreateLoanResponse{}
	mi := &file_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLoanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLoanResponse) ProtoMessage() {}

func (x *CreateLoanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLoanResponse.ProtoReflect.Descriptor instead.
func (*CreateLoanResponse) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLoanResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetOutstandingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoanId        string                 `protobuf:"bytes,1,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOutstandingRequest) Reset() {
	*x = GetOutstandingRequest{}
	mi := &file_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOutstandingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOutstandingRequest) ProtoMessage() {}

func (x *GetOutstandingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOutstandingRequest.ProtoReflect.Descriptor instead.
func (*GetOutstandingRequest) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{2}
}

func (x *GetOutstandingRequest) GetLoanId() string {
	if x != nil {
		return x.LoanId
	}
	return ""
}

type GetOutstandingResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OutstandingAmount int64                  `protobuf:"varint,1,opt,name=outstanding_amount,json=outstandingAmount,proto3" json:"outstanding_amount,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetOutstandingResponse) Reset() {
	*x = GetOutstandingResponse{}
	mi := &file_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOutstandingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOutstandingResponse) ProtoMessage() {}

func (x *GetOutstandingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOutstandingResponse.ProtoReflect.Descriptor instead.
func (*GetOutstandingResponse) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{3}
}

func (x *GetOutstandingResponse) GetOutstandingAmount() int64 {
	if x != nil {
		return x.OutstandingAmount
	}
	return 0
}

type IsDelinquentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoanId        string                 `protobuf:"bytes,1,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsDelinquentRequest) Reset() {
	*x = IsDelinquentRequest{}
	mi := &file_billing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsDelinquentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsDelinquentRequest) ProtoMessage() {}

func (x *IsDelinquentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsDelinquentRequest.ProtoReflect.Descriptor instead.
func (*IsDelinquentRequest) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{4}
}

func (x *IsDelinquentRequest) GetLoanId() string {
	if x != nil {
		return x.LoanId
	}
	return ""
}

type IsDelinquentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delinquent    bool                   `protobuf:"varint,1,opt,name=delinquent,proto3" json:"delinquent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsDelinquentResponse) Reset() {
	*x = IsDelinquentResponse{}
	mi := &file_billing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsDelinquentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsDelinquentResponse) ProtoMessage() {}

func (x *IsDelinquentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsDelinquentResponse.ProtoReflect.Descriptor instead.
func (*IsDelinquentResponse) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{5}
}

func (x *IsDelinquentResponse) GetDelinquent() bool {
	if x != nil {
		return x.Delinquent
	}
	return false
}

type MakePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoanId        string                 `protobuf:"bytes,1,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakePaymentRequest) Reset() {
	*x = MakePaymentRequest{}
	mi := &file_billing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakePaymentRequest) ProtoMessage() {}

func (x *MakePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakePaymentRequest.ProtoReflect.Descriptor instead.
func (*MakePaymentRequest) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{6}
}

func (x *MakePaymentRequest) GetLoanId() string {
	if x != nil {
		return x.LoanId
	}
	return ""
}

func (x *MakePaymentRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type MakePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakePaymentResponse) Reset() {
	*x = MakePaymentResponse{}
	mi := &file_billing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakePaymentResponse) ProtoMessage() {}

func (x *MakePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakePaymentResponse.ProtoReflect.Descriptor instead.
func (*MakePaymentResponse) Descriptor() ([]byte, []int) {
	return file_billing_proto_rawDescGZIP(), []int{7}
}

func (x *MakePaymentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_billing_proto protoreflect.FileDescriptor

const file_billing_proto_rawDesc = "" +
	"\n" +
	"\rbilling.proto\x12\x0ebilling_engine\"\xc0\x01\n" +
	"\x11CreateLoanRequest\x12\x17\n" +
	"\aloan_id\x18\x01 \x01(\tR\x06loanId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12)\n" +
	"\x10principal_amount\x18\x03 \x01(\x03R\x0fprincipalAmount\x12!\n" +
	"\ftenure_weeks\x18\x04 \x01(\x05R\vtenureWeeks\x12#\n" +
	"\rinterest_rate\x18\x05 \x01(\x01R\finterestRate\".\n" +
	"\x12CreateLoanResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"0\n" +
	"\x15GetOutstandingRequest\x12\x17\n" +
	"\aloan_id\x18\x01 \x01(\tR\x06loanId\"G\n" +
	"\x16GetOutstandingResponse\x12-\n" +
	"\x12outstanding_amount\x18\x01 \x01(\x03R\x11outstandingAmount\".\n" +
	"\x13IsDelinquentRequest\x12\x17\n" +
	"\aloan_id\x18\x01 \x01(\tR\x06loanId\"6\n" +
	"\x14IsDelinquentResponse\x12\x1e\n" +
	"\n" +
	"delinquent\x18\x01 \x01(\bR\n" +
	"delinquent\"E\n" +
	"\x12MakePaymentRequest\x12\x17\n" +
	"\aloan_id\x18\x01 \x01(\tR\x06loanId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"/\n" +
	"\x13MakePaymentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xf9\x02\n" +
	"\x0eBillingService\x12S\n" +
	"\n" +
	"CreateLoan\x12!.billing_engine.CreateLoanRequest\x1a\".billing_engine.CreateLoanResponse\x12_\n" +
	"\x0eGetOutstanding\x12%.billing_engine.GetOutstandingRequest\x1a&.billing_engine.GetOutstandingResponse\x12Y\n" +
	"\fIsDelinquent\x12#.billing_engine.IsDelinquentRequest\x1a$.billing_engine.IsDelinquentResponse\x12V\n" +
	"\vMakePayment\x12\".billing_engine.MakePaymentRequest\x1a#.billing_engine.MakePaymentResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_billing_proto_rawDescOnce sync.Once
	file_billing_proto_rawDescData []byte
)

func file_billing_proto_rawDescGZIP() []byte {
	file_billing_proto_rawDescOnce.Do(func() {
		file_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_proto_rawDesc), len(file_billing_proto_rawDesc)))
	})
	return file_billing_proto_rawDescData
}

var file_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_billing_proto_goTypes = []any{
	(*CreateLoanRequest)(nil),      // 0: billing_engine.CreateLoanRequest
	(*CreateLoanResponse)(nil),     // 1: billing_engine.CreateLoanResponse
	(*GetOutstandingRequest)(nil),  // 2: billing_engine.GetOutstandingRequest
	(*GetOutstandingResponse)(nil), // 3: billing_engine.GetOutstandingResponse
	(*IsDelinquentRequest)(nil),    // 4: billing_engine.IsDelinquentRequest
	(*IsDelinquentResponse)(nil),   // 5: billing_engine.IsDelinquentResponse
	(*MakePaymentRequest)(nil),     // 6: billing_engine.MakePaymentRequest
	(*MakePaymentResponse)(nil),    // 7: billing_engine.MakePaymentResponse
}
var file_billing_proto_depIdxs = []int32{
	0, // 0: billing_engine.BillingService.CreateLoan:input_type -> billing_engine.CreateLoanRequest
	2, // 1: billing_engine.BillingService.GetOutstanding:input_type -> billing_engine.GetOutstandingRequest
	4, // 2: billing_engine.BillingService.IsDelinquent:input_type -> billing_engine.IsDelinquentRequest
	6, // 3: billing_engine.BillingService.MakePayment:input_type -> billing_engine.MakePaymentRequest
	1, // 4: billing_engine.BillingService.CreateLoan:output_type -> billing_engine.CreateLoanResponse
	3, // 5: billing_engine.BillingService.GetOutstanding:output_type -> billing_engine.GetOutstandingResponse
	5, // 6: billing_engine.BillingService.IsDelinquent:output_type -> billing_engine.IsDelinquentResponse
	7, // 7: billing_engine.BillingService.MakePayment:output_type -> billing_engine.MakePaymentResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_billing_proto_init() }
func file_billing_proto_init() {
	if File_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_proto_rawDesc), len(file_billing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billing_proto_goTypes,
		DependencyIndexes: file_billing_proto_depIdxs,
		MessageInfos:      file_billing_proto_msgTypes,
	}.Build()
	File_billing_proto = out.File
	file_billing_proto_goTypes = nil
	file_billing_proto_depIdxs = nil
}
